/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.MenuDAO;
import dao.PerfilDAO;
import dao.PermisosPerfilesDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Menu;
import modelo.Perfil;
import modelo.PerfilesPer;
import modelo.PerfilesPermisos;



/**
 *
 * @author yzeballos
 */
public class FrmPerfil extends javax.swing.JInternalFrame {

    PerfilDAO perfilDAo= new PerfilDAO();
    MenuDAO menuDao = new MenuDAO();
    PermisosPerfilesDAO permisosPerfilesDao = new PermisosPerfilesDAO();
    Perfil perfil;
    /**
     * Creates new form FrmPerfil
     */
    public FrmPerfil() {
        initComponents();
        Listar(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tpPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListado = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnNuevo1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnPermisos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbListadoMenus = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Perfiles de usuario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tpPanel.setName(""); // NOI18N

        tbListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre Perfil", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbListado);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnNuevo1.setText("Eliminar");
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))))
        );

        tpPanel.addTab("Listado", jPanel1);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Id:");

        jLabel2.setText("Nombre de Perfil:");

        btnAgregar.setText("Grabar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel5.setText("Descripción:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        btnPermisos.setText("Permisos");
        btnPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermisosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        tpPanel.addTab("Mantenimiento", jPanel2);

        tbListadoMenus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbListadoMenus.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbListadoMenus.setMinimumSize(new java.awt.Dimension(10, 0));
        jScrollPane4.setViewportView(tbListadoMenus);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        tpPanel.addTab("Permisos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        PasarDatos();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.tpPanel.setSelectedIndex(1);
        Limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        Eliminar();
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        Listar(Integer.parseInt(this.txtBuscar.getText()));
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        if(this.txtId.isEnabled()){
            Agregar();
        }else{
            Actualizar();
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Limpiar();
        this.tpPanel.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermisosActionPerformed
       int id = ObtenerCodigo();
       ListarPermisos(id);
    }//GEN-LAST:event_btnPermisosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JButton btnPermisos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbListado;
    private javax.swing.JTable tbListadoMenus;
    private javax.swing.JTabbedPane tpPanel;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

private void Limpiar(){
    this.txtId.setText("");
    this.txtDescripcion.setText("");
    this.txtNombre.setText("");
    this.txtId.setEnabled(true); 
}

private void Listar(int codigo){ // si codigo= 0 : listar todo , sino buscar las concidencias
    
     this.tpPanel.setSelectedIndex(0);
     tbListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre Perfil","Descripcion"
            }
        ));

    DefaultTableModel modelo = (DefaultTableModel)this.tbListado.getModel();
    
    List<Perfil> lista = new ArrayList<>();
    try {
         if(codigo == 0)
            lista = perfilDAo.Listar();
         else
            lista = perfilDAo.Listar(codigo);
         
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        return;
    }
    
    Object[] fila = new Object[modelo.getColumnCount()];
    
    for(int i = 0; i <lista.size(); i++){
        fila[0] = lista.get(i).getId();
        fila[1] = lista.get(i).getNombrePerfil();
        fila[2] = lista.get(i).getDescripcion();
        modelo.addRow(fila);
    }
}

private void Agregar(){
    
    boolean rpt = false;
    int id = "".equals(this.txtId.getText()) ? 0 : Integer.parseInt(this.txtId.getText());
    String nombrePerfil = this.txtNombre.getText();
    String descripcion = this.txtDescripcion.getText();

    perfil = new Perfil(id, nombrePerfil,descripcion);
    
    

    if(rpt){
        JOptionPane.showMessageDialog(null, "Perfil agregado correctamente");
    }else{
        JOptionPane.showMessageDialog(null, "No se agrego el Perfil");
    }
    
    Limpiar();
    Listar(0);
}

private void PasarDatos(){
    
    int id= ObtenerCodigo();
    
    if(id == 0)
        return;
    
    try {
        perfil = perfilDAo.Buscar(id);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    
    
    this.txtId.setEnabled(false);
    this.txtId.setText("" + perfil.getId());
    this.txtDescripcion.setText(perfil.getDescripcion());
    this.txtNombre.setText(perfil.getNombrePerfil());
    this.tpPanel.setSelectedIndex(1);
}

private void Actualizar(){
    boolean rpt = false;
    int id = Integer.parseInt(this.txtId.getText());
    String nombrePerfil = this.txtNombre.getText();
    String descripcion = this.txtDescripcion.getText();

    perfil = new Perfil(id, nombrePerfil,descripcion);
    
    List<Object> lista  = new ArrayList<>();
     //Agregar Permisos
//     try {
//        permisosPerfilesDao.Eliminar(id);
//        
//    } catch (Exception e) {
//         JOptionPane.showMessageDialog(this, e.getMessage());
//    }
    for (int i = 0; i < this.tbListadoMenus.getRowCount(); i++) {
            for (int j = 0; j <  this.tbListadoMenus.getColumnCount(); j++) {
		lista.add(this.tbListadoMenus.getValueAt(i, j));
		}
            System.out.println();
	}
    
    try {
        rpt = perfilDAo.Agregar(perfil);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        return;
    }
    
    try {
        rpt = perfilDAo.Actualizar(perfil);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        return;
    }
    

    if(rpt){
        JOptionPane.showMessageDialog(null, "Perfil actualizado correctamente");
    }else{
        JOptionPane.showMessageDialog(null, "No se actualizo el Perfil");
    }
    
    Limpiar();
    Listar(0);
}

private int ObtenerCodigo(){
    
    if(this.tbListado.getSelectedRow() == -1){
        JOptionPane.showMessageDialog(this, "Seleccione una Categoría");
        return  0;
    }
    
    DefaultTableModel modelo = (DefaultTableModel)this.tbListado.getModel();
    String codigo=String.valueOf(modelo.getValueAt(tbListado.getSelectedRow(),0));
    
    return Integer.parseInt(codigo);
}

private void Eliminar(){
    boolean rpt= false;
    
    int id = ObtenerCodigo();
    
     if(id == 0)
        return;
    
    if(JOptionPane.showConfirmDialog(this, "¿Estas seguro de Eliminar?") == 0){
        
        try {
            rpt = perfilDAo.Eliminar(id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        if(rpt){
            JOptionPane.showMessageDialog(this, "Categoria Eliminado");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo eliminar la categoria");
        }
    }
    
    Listar(0);
}

private void Buscar(int id){ 
    Listar(id);
}
 
private void ListarPermisos(int idPerfil){ // si codigo= 0 : listar todo , sino buscar las concidencias
    
     this.tpPanel.setSelectedIndex(2);
      tbListadoMenus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre menú","Activado","Lectura","Escritura","Eliminacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class,java.lang.Boolean.class, java.lang.Boolean.class,java.lang.Boolean.class,java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });

    DefaultTableModel modelo = (DefaultTableModel)this.tbListadoMenus.getModel();
    
    List<Menu> listaMenus = new ArrayList<>();
     List<PerfilesPermisos> listaPerfilesPermisos = new ArrayList<>();
    try {
         listaMenus = menuDao.Listar();//Perfil del usuario
         listaPerfilesPermisos =  listaPermisos(idPerfil);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        return;
    }
    
    Object[] fila = new Object[modelo.getColumnCount()];
    
    for(int i = 0; i <listaMenus.size(); i++){
         for(int j = 0; j <listaPerfilesPermisos.size(); j++){
             if(listaMenus.get(i).getId() == listaPerfilesPermisos.get(j).getMenu().getId()){
                 listaMenus.get(i).setActivado(listaPerfilesPermisos.get(j).isActivado());
                 listaMenus.get(i).setLectura(listaPerfilesPermisos.get(j).isLectura());
                 listaMenus.get(i).setEscritura(listaPerfilesPermisos.get(j).isEscritura());
                 listaMenus.get(i).setEliminacion(listaPerfilesPermisos.get(j).isEliminacion());
             }
         }
    }
    for ( int i = 0; i<listaMenus.size();i++) {
         fila[0] = listaMenus.get(i) .getId();
         fila[1] = listaMenus.get(i).getDescripcion();
         fila[2] = listaMenus.get(i).isActivado();
         fila[3] = listaMenus.get(i).isLectura();
         fila[4] = listaMenus.get(i).isEscritura();
         fila[5] = listaMenus.get(i).isEliminacion();
         modelo.addRow(fila);
    }
    
    tbListadoMenus.getColumnModel().getColumn(0).setPreferredWidth(40);
    tbListadoMenus.getColumnModel().getColumn(1).setPreferredWidth(200);
    tbListadoMenus.getColumnModel().getColumn(2).setPreferredWidth(80);
    tbListadoMenus.getColumnModel().getColumn(3).setPreferredWidth(80);
    tbListadoMenus.getColumnModel().getColumn(4).setPreferredWidth(80);
    tbListadoMenus.getColumnModel().getColumn(5).setPreferredWidth(80);
}

private List<PerfilesPermisos> listaPermisos(int codigo){
    
    List<PerfilesPermisos> lista =  new ArrayList<>();
    PermisosPerfilesDAO permisoDao = new PermisosPerfilesDAO();
    
    try {
        lista = permisoDao.Listar(codigo);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    
    return lista;
}
 
 
 
    
}
