/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.PerfilDAO;
import dao.UsuarioDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.HashSalt;
import modelo.Perfil;
import modelo.Usuario;

/**
 *
 * @author yzeballos
 */
public class FrmUsuario extends javax.swing.JInternalFrame {

    UsuarioDAO usuarioDao = new UsuarioDAO();
    Usuario usuario;
    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuario() {
        initComponents();
        LlenarCombo();
        Listar(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tpPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListado = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cboPerfil = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        txtNombrePerfil = new javax.swing.JTextField();
        chkCambiarContraseña = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuarios");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        tpPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tpPanel.setName(""); // NOI18N

        tbListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Categoria"
            }
        ));
        tbListado.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbListado.setMinimumSize(new java.awt.Dimension(10, 0));
        jScrollPane1.setViewportView(tbListado);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))))
        );

        tpPanel.addTab("Listado", jPanel1);

        jPanel2.setLayout(null);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(260, 190, 78, 33);

        txtId.setEnabled(false);
        jPanel2.add(txtId);
        txtId.setBounds(140, 38, 68, 20);
        jPanel2.add(txtUsuario);
        txtUsuario.setBounds(140, 64, 230, 20);

        jLabel1.setText("Id:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(28, 44, 14, 14);

        jLabel2.setText("Usuario:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(28, 67, 40, 14);

        btnAgregar.setText("Grabar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar);
        btnAgregar.setBounds(160, 190, 78, 33);

        jLabel5.setText("Perfil");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(28, 145, 24, 14);

        jPanel2.add(cboPerfil);
        cboPerfil.setBounds(140, 142, 230, 20);

        jLabel6.setText("Contraseña:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(28, 93, 60, 14);

        jLabel7.setText("Nombre de usuario:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(28, 119, 94, 14);
        jPanel2.add(txtContrasena);
        txtContrasena.setBounds(140, 90, 230, 20);
        jPanel2.add(txtNombrePerfil);
        txtNombrePerfil.setBounds(140, 116, 230, 20);

        chkCambiarContraseña.setText("Cambiar Contraseña");
        chkCambiarContraseña.setEnabled(false);
        chkCambiarContraseña.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkCambiarContraseñaStateChanged(evt);
            }
        });
        jPanel2.add(chkCambiarContraseña);
        chkCambiarContraseña.setBounds(380, 90, 123, 23);

        tpPanel.addTab("Mantenimiento", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tpPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        PasarDatos();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.tpPanel.setSelectedIndex(1);
        Limpiar();
        this.txtContrasena.setEnabled(true);
        this.chkCambiarContraseña.setSelected(true);
        this.chkCambiarContraseña.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        if(this.txtBuscar.getText().equals(""))
            Listar(0);
        else    
           Buscar(Integer.parseInt(this.txtBuscar.getText()));
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Limpiar();
        this.tpPanel.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(this.txtId.getText().equals("")){
            Agregar();
        }else{
            Actualizar();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void chkCambiarContraseñaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkCambiarContraseñaStateChanged
        this.txtContrasena.setEnabled(this.chkCambiarContraseña.isSelected());
    }//GEN-LAST:event_chkCambiarContraseñaStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<Perfil> cboPerfil;
    private javax.swing.JCheckBox chkCambiarContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListado;
    private javax.swing.JTabbedPane tpPanel;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombrePerfil;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables


    private void Limpiar(){
        this.txtBuscar.setText("");
        this.txtContrasena.setText("");
        this.cboPerfil.setSelectedIndex(0);
        this.txtId.setText("");
        this.txtNombrePerfil.setText("");
        this.txtUsuario.setText("");
        this.txtContrasena.setEnabled(true);
    }
    
    private void LlenarCombo(){
        PerfilDAO perfilDao= new PerfilDAO();
        List<Perfil> listaPerfil = new ArrayList<>();
        try {
             listaPerfil = perfilDao.Listar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       
        for (Perfil perfil : listaPerfil) {
            cboPerfil.addItem(perfil);
        }  
    }
    
    private void Listar(int codigo){ // si codigo= 0 : listar todo , sino buscar las concidencias

         this.tpPanel.setSelectedIndex(0);
         tbListado.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "ID", "Usuario","Perfil","Nombre"
                }
            ));

        DefaultTableModel modelo = (DefaultTableModel)this.tbListado.getModel();

        List<Usuario> lista = new ArrayList<>();

        try {
            if(codigo == 0)
                lista = usuarioDao.Listar();
             else
                lista = usuarioDao.Listar(codigo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        Object[] fila = new Object[modelo.getColumnCount()];

        for(int i = 0; i <lista.size(); i++){
            fila[0] = lista.get(i).getId();
            fila[1] = lista.get(i).getUserName();
            fila[2] = lista.get(i).getPerfil().getNombrePerfil();
            fila[3] = lista.get(i).getNombre();
            modelo.addRow(fila);
        }
        
        tbListado.getColumnModel().getColumn(0).setPreferredWidth(40);
        tbListado.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbListado.getColumnModel().getColumn(2).setPreferredWidth(200);
        tbListado.getColumnModel().getColumn(3).setPreferredWidth(200);
    }
    
    private void Agregar(){
        
        boolean rpt = false;
        String username = this.txtUsuario.getText();
        String nombre = this.txtNombrePerfil.getText();
        Perfil perfil = (Perfil)cboPerfil.getSelectedItem();
        this.usuario = new Usuario(0,username, ObtenerContrasena(), nombre, perfil);
        
        try {
            rpt = usuarioDao.Agregar(usuario);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        if(rpt)
            JOptionPane.showMessageDialog(null, "Usuario agregado correctamente");
        else
            JOptionPane.showMessageDialog(null, "No se agrego el usuario");
        
        Limpiar();
        Listar(0);
    }
    
    private void Actualizar(){
        
        boolean rpt = false;
        this.txtContrasena.setEnabled(true);
        int codigo = this.txtId.getText().equals("") ? 0 : Integer.parseInt(this.txtId.getText());
        String username = this.txtUsuario.getText();
        String nombre = this.txtNombrePerfil.getText();
        Perfil perfil = (Perfil)cboPerfil.getSelectedItem();
        this.usuario = new Usuario(codigo,username, ObtenerContrasena(), nombre, perfil);
        
        try {
            rpt = usuarioDao.Actualizar(usuario,this.chkCambiarContraseña.isSelected());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        if(rpt)
            JOptionPane.showMessageDialog(null, "Usuario se grabo correctamente");
        else
            JOptionPane.showMessageDialog(null, "No se grabo el usuario");
        
       Limpiar();
       Listar(0);
    }
    
     private void Eliminar(){
        boolean rpt= false;

        int codigo = ObtenerCodigo();

         if(codigo == 0)
            return;

        if(JOptionPane.showConfirmDialog(this, "¿Estas seguro de Eliminar?") == 0){
            
            try {
                 rpt = usuarioDao.Eliminar(codigo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
           
            if(rpt)
                JOptionPane.showMessageDialog(this, "Usuario Eliminado");
            else
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el Usuario");
        }

        Listar(0);
    }
    
    private void PasarDatos(){
        this.chkCambiarContraseña.setEnabled(true);
        int codigo= ObtenerCodigo();

        if(codigo == 0)
            return;

        try {
           usuario = usuarioDao.Buscar(codigo); 
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this, e.getMessage());
           return;
        }
        
        this.txtId.setText(""+usuario.getId());
        this.txtNombrePerfil.setText(usuario.getNombre());
        this.txtUsuario.setText(usuario.getUserName());
        this.txtContrasena.setText(usuario.getContrasena());
       
        for (int i=0;i < this.cboPerfil.getItemCount() ;i++) {
         
            if(cboPerfil.getItemAt(i).getId() == usuario.getPerfil().getId()){
                this.cboPerfil.setSelectedIndex(i);
            }
        }
        
        this.tpPanel.setSelectedIndex(1);
    }
    
    private int ObtenerCodigo(){
        if(this.tbListado.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un usuario");
            return 0;
        }

        DefaultTableModel modelo = (DefaultTableModel)this.tbListado.getModel();
        String codigo=String.valueOf(modelo.getValueAt(tbListado.getSelectedRow(),0));

        return Integer.parseInt(codigo);
    }
    
    private String ObtenerContrasena(){
        StringBuilder contrasenaBuilder = new StringBuilder();
        char[] arrayContrasena = this.txtContrasena.getPassword();

        for (char c : arrayContrasena) {
            contrasenaBuilder.append(c).toString();
        }
        String contrasena = contrasenaBuilder.toString();
        return contrasena;
    }
    
     private void Buscar(int codigo){ 
        Listar(codigo);
    }
    
}
